## 初期設定

In [1]:
from mymodule import MLs
from mymodule import myfunc as mf
import numpy as np
import pandas as pd
import glob
import os
from dotenv import load_dotenv
load_dotenv()
# root_dir = os.environ["root_dir"]
root_dir = "../"

データの参照先の設定、インスタンス作成

In [2]:
TARGET = "magxy" #ALTIMAGES等のディレクトリにくっつけます
#それぞれ1番最後の'/'は忘れずつけること
ALTIMAGES0 = root_dir + "imgout/0117_not/"#リコネクションなし分割済データフォルダ.makesepnpy.ipynbであらかじめ分割データを入れておく
ALTIMAGES1 = root_dir + "imgout/0117_1X/"#リコネクションあり分割済データフォルダ.makesepnpy.ipynbであらかじめ分割データを入れておく
LABEL_SOURCE0 = root_dir + "txt/labels0/"#リコネクションありのラベリングcsvのあるフォルダ
LABEL_SOURCE1 = root_dir + "txt/labels1X/"#リコネクションなしのラベリングcsvのあるフォルダ
IMGSHAPE = (100,20)#出来れば画像サイズはすべて同じで合ってほしい。違うサイズが混じる場合は最も多いサイズを指定すること
# IMGSHAPE = (100,10,2)
DO_PCA = False #データ圧縮。IMGSHAPEと、データサイズが途方もなく多ければTrueにする。
randomstate = None #学習時のパラメータ。初期値はNone。結果を固定したければ1とかに設定する。

ML = MLs.ML(TARGET, ALTIMAGES0, ALTIMAGES1, LABEL_SOURCE0, LABEL_SOURCE1, IMGSHAPE, DO_PCA,randomstate=randomstate)

In [2]:
#画像出力用関数
import cv2
def trimBMP(bmp, outname, xcenter, ycenter):
    bmpXlen = 1799
    bmpYlen = 570
    npyXlen = 257
    npyYlen = 1025
    xrange = 10/2
    yrange = 100/2
    def bmplocx(npylocx):
        return int(npylocx*bmpXlen/npyXlen)
    def bmplocy(npylocy):
        return int(bmpYlen-(bmpYlen*npylocy/npyYlen))
    xup, xdown = bmplocx(xcenter + xrange), bmplocx(xcenter - xrange)
    yup, ydown = bmplocy(ycenter + yrange), bmplocy(ycenter - yrange)
    im = cv2.imread(bmp,cv2.IMREAD_GRAYSCALE)
    name = os.path.basename(bmp)
    separated_im = im[yup:ydown,xdown:xup]
    cv2.imwrite(outname, separated_im)

def dotrimBMP(df, outdir):
    for npypath, y, predict in zip(df["path"], df["y"], df["predict"]):
        status = f'y{y[:1]}pred{predict[:1]}'
        pattern = re.compile('[a-zA-Z_]+_')
        target = pattern.search(os.path.basename(npypath)).group()[:-1]

        pathPattern = re.compile('_\d+\.\d+\.\d+_')
        rangePattern =re.compile('_\d+\.\d+\.npy')
        pathstr = pathPattern.search(npypath).group()[1:-1]
        rangestr = rangePattern.search(npypath).group()[1:-4]
        path = pathstr.split(".")
        licpath = f"../imgout/ohnolic/snap{path[0]}/lic_snap{path[0]}.{'{0:02d}'.format(int(path[1]))}.{'{0:02d}'.format(int(path[2]))}.bmp"
        xycenter = rangestr.split(".")
        if not os.path.exists(outdir + f"{target}/{status}"):
            if not os.path.exists(outdir + f"{target}"):
                os.mkdir(outdir + f"{target}")
            os.mkdir(outdir + f"{target}/{status}")
        outname = outdir + f"{target}/{status}/{str.replace(os.path.basename(npypath),'.npy', '.bmp')}"
        trimBMP(licpath, outname, int(xycenter[0]), int(xycenter[1]))       


### 例

In [15]:
#学習
#モジュールに書いてるコードで実行
# model = ML.linearSVC()   
# model =ML.kneighbors()
# model =ML.rbfSVC()
# model =ML.XGBoost()

#or
#自由に記述し、MLクラスを利用して実行
from sklearn.svm import LinearSVC
def mylinearSVC(self):    
        model = LinearSVC(C=0.3, random_state=self.randomstate) # インスタンスを生成
        model.fit(self.X_train, self.y_train) # モデルの学習
        # 学習データに対する精度
        print("Train :", model.score(self.X_train, self.y_train)) 
        # テストデータに対する精度
        print("Test :", model.score(self.X_test, self.y_test)) 
        print(model.predict(self.X_test))
        pred = model.predict(self.X_test)
        svmres = pd.DataFrame(np.array([self.path_test, self.y_test, pred]).T, columns=["path", "y", "predict"])
        # print(classification_report(self.y_test, pred))
        return model
svm = mylinearSVC(ML)

Train : 0.9762275915822292
Test : 0.9725324479323876
[0. 0. 0. ... 1. 1. 1.]


c:\Users\lkxl1\Anaconda3\lib\site-packages\sklearn\svm\_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


In [ ]:
#参照可能なもの
ML.TARGET = TARGET#magfieldx, pressure,,,
ML.PATH1
ML.PATH0
ML.ALLTARINDATA0#データ参照先フォルダ
ML.ALLTARINDATA1
ML.PATH0TEST#テストデータ一覧
ML.PATH1TEST
ML.PATH0TRAIN#学習データ
ML.PATH1TRAIN
ML.X_test
ML.y_test
ML.path_test
ML.X_train
ML.y_train
ML.path_train
#後から変更可能なもの
ML.randomstate = 1

['../imgout/test1227/magfieldx/magfieldx_49.10.3_47.773.npy',
 '../imgout/test1227/magfieldx/magfieldx_49.10.6_47.773.npy',
 '../imgout/test1227/magfieldx/magfieldx_49.12.13_147.452.npy',
 '../imgout/test1227/magfieldx/magfieldx_49.13.13_42.607.npy',
 '../imgout/test1227/magfieldx/magfieldx_49.7.13_127.625.npy',
 '../imgout/test1227/magfieldx/magfieldx_49.10.4_47.773.npy',
 '../imgout/test1227/magfieldx/magfieldx_49.13.13_102.420.npy',
 '../imgout/test1227/magfieldx/magfieldx_49.10.3_82.620.npy']

In [ ]:
#学習モデルをファイルに保存、読み込み例
import pickle
path = "pickletest"

file = open(path, "wb") 
pickle.dump(svm, file)
file.close

with open(path, 'rb') as f:
    dict = pickle.load(f)
print(svm)

LinearSVC(C=0.3)


## 以下自由に

In [9]:
# model = ML.XGBoost()  
model = ML.linearSVC()
# model = ML.kneighbors()
# model = ML.rbfSVC()
df = model[1]
df1 = df[df["y"] != df["predict"]]
dotrimBMP(df1, "../imgout/0119test/")
df1

Train : 0.9773967264224473
Test : 0.9782674313311198
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.96      0.96      0.96       967
         1.0       0.99      0.98      0.98      2346

    accuracy                           0.98      3313
   macro avg       0.97      0.97      0.97      3313
weighted avg       0.98      0.98      0.98      3313



c:\Users\lkxl1\Anaconda3\lib\site-packages\sklearn\svm\_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


path    y predict
48    ../imgout/0117_not/magxy/magxy_77.45.9_39.369.npy  0.0     1.0
70    ../imgout/0117_not/magxy/magxy_77.47.9_39.369.npy  0.0     1.0
107   ../imgout/0117_not/magxy/magxy_77.24.5_158.554...  0.0     1.0
125   ../imgout/0117_not/magxy/magxy_77.23.9_115.498...  0.0     1.0
166   ../imgout/0117_not/magxy/magxy_49.19.10_65.546...  0.0     1.0
...                                                 ...  ...     ...
2577   ../imgout/0117_1X/magxy/magxy_77.34.5_37.548.npy  1.0     0.0
2909  ../imgout/0117_1X/magxy/magxy_77.6.11_213.559.npy  1.0     0.0
2916  ../imgout/0117_1X/magxy/magxy_77.48.10_241.570...  1.0     0.0
3140  ../imgout/0117_1X/magxy/magxy_49.58.13_134.505...  1.0     0.0
3231   ../imgout/0117_1X/magxy/magxy_49.24.9_25.480.npy  1.0     0.0

[72 rows x 3 columns]

In [ ]:
import pickle
picout = root_dir + "MLres/"

for target in ["density", "enstrophy", "pressure","magfieldx", "magfieldy", "velocityx","velocityy"]:
    for tag, altimages1, labelsources1 in [("X","imgout/0117_1X/","txt/labels1X/"), ("O","imgout/0117_1O/", "txt/labels1O/")]:
        TARGET = target
        #それぞれ1番最後の'/'は忘れずつけること
        ALTIMAGES0 = root_dir + "imgout/0117_not/"#リコネクションなし分割済データフォルダ
        ALTIMAGES1 = root_dir + altimages1#リコネクションあり分割済データフォルダ
        LABEL_SOURCE0 = root_dir + "txt/labels0/"#リコネクションありのラベリングcsvのあるフォルダ
        LABEL_SOURCE1 = root_dir + labelsources1#リコネクションなしのラベリングcsvのあるフォルダ
        IMGSHAPE = (100,10)#出来れば画像サイズはすべて同じで合ってほしい。違うサイズが混じる場合は最も多いサイズを指定すること
        DO_PCA = False #データ圧縮。IMGSHAPEと、データサイズが途方もなく多ければTrueにする。
        randomstate = None #学習時のパラメータ。初期値はNone。結果を固定したければ1とかに設定する。

        ML = MLs.ML(TARGET, ALTIMAGES0, ALTIMAGES1, LABEL_SOURCE0, LABEL_SOURCE1, IMGSHAPE, DO_PCA,randomstate=randomstate)
        def savemodel(model, methodname):
            picout = root_dir + "MLres/"
            path = picout + "model_" + target + "_" + tag + "_" + methodname
            file = open(path, "wb") 
            pickle.dump(model, file)
            file.close()
            print("model_" + target + "_" + tag + "_" + methodname+"\n")
            print("------------------\n\n\n\n")
        model = ML.linearSVC()   
        savemodel(model, "linearSVC")
        model = ML.kneighbors()
        savemodel(model, "kneighbors")
        model = ML.rbfSVC()
        savemodel(model, "rbfSVC")
        model = ML.XGBoost()
        savemodel(model, "XGBoost")

PCA 非実施


c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.8829566121070408
Test : 0.86296408089345
[0. 0. 1. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.83      0.67      0.74       967
         1.0       0.87      0.94      0.91      2346

    accuracy                           0.86      3313
   macro avg       0.85      0.81      0.82      3313
weighted avg       0.86      0.86      0.86      3313

model_density_X_linearSVC

------------------




Train : 0.9506365289685632
Test : 0.9441593721702385
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.94      0.86      0.90       967
         1.0       0.94      0.98      0.96      2346

    accuracy                           0.94      3313
   macro avg       0.94      0.92      0.93      3313
weighted avg       0.94      0.94      0.94      3313

model_density_X_kneighbors

------------------




Train : 0.9580410496232787
Test : 0.9387262300030184
[0. 0. 0. ... 1. 1. 1.]
              pr

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.9350553505535055
Test : 0.9179539993134226
[0. 1. 0. ... 1. 1. 0.]
              precision    recall  f1-score   support

         0.0       0.87      0.89      0.88       967
         1.0       0.94      0.93      0.94      1946

    accuracy                           0.92      2913
   macro avg       0.91      0.91      0.91      2913
weighted avg       0.92      0.92      0.92      2913

model_density_O_linearSVC

------------------




Train : 0.9176383763837639
Test : 0.9196704428424305
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.84      0.93      0.88       967
         1.0       0.96      0.91      0.94      1946

    accuracy                           0.92      2913
   macro avg       0.90      0.92      0.91      2913
weighted avg       0.92      0.92      0.92      2913

model_density_O_kneighbors

------------------




Train : 0.9174907749077491
Test : 0.9117748026089941
[0. 0. 0. ... 1. 1. 0.]
              

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.8695765133800988
Test : 0.8424388771506188
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.77      0.65      0.71       967
         1.0       0.87      0.92      0.89      2346

    accuracy                           0.84      3313
   macro avg       0.82      0.79      0.80      3313
weighted avg       0.84      0.84      0.84      3313

model_enstrophy_X_linearSVC

------------------




Train : 0.6291244479085477
Test : 0.6272260790824027
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.44      0.96      0.60       967
         1.0       0.97      0.49      0.65      2346

    accuracy                           0.63      3313
   macro avg       0.70      0.72      0.63      3313
weighted avg       0.81      0.63      0.64      3313

model_enstrophy_X_kneighbors

------------------




Train : 0.7620161080800207
Test : 0.7416239058255357
[0. 1. 1. ... 1. 1. 1.]
          

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.9297416974169742
Test : 0.8990731204943357
[0. 0. 1. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.85      0.84      0.85       967
         1.0       0.92      0.93      0.92      1946

    accuracy                           0.90      2913
   macro avg       0.89      0.89      0.89      2913
weighted avg       0.90      0.90      0.90      2913

model_enstrophy_O_linearSVC

------------------




Train : 0.8516605166051661
Test : 0.826295914864401
[1. 0. 1. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.73      0.75      0.74       967
         1.0       0.87      0.87      0.87      1946

    accuracy                           0.83      2913
   macro avg       0.80      0.81      0.80      2913
weighted avg       0.83      0.83      0.83      2913

model_enstrophy_O_kneighbors

------------------




Train : 0.7964575645756458
Test : 0.7651905252317199
[1. 1. 1. ... 1. 1. 1.]
           

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.9495972979994803
Test : 0.9396317536975551
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.94      0.85      0.89       967
         1.0       0.94      0.98      0.96      2346

    accuracy                           0.94      3313
   macro avg       0.94      0.91      0.92      3313
weighted avg       0.94      0.94      0.94      3313

model_pressure_X_linearSVC

------------------




Train : 0.8254091971940763
Test : 0.8321762752792031
[0. 1. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.95      0.45      0.61       967
         1.0       0.81      0.99      0.89      2346

    accuracy                           0.83      3313
   macro avg       0.88      0.72      0.75      3313
weighted avg       0.85      0.83      0.81      3313

model_pressure_X_kneighbors

------------------




Train : 0.9319303715250714
Test : 0.9257470570479928
[0. 0. 0. ... 1. 1. 1.]
            

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.9998523985239852
Test : 0.9996567112941984
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       967
         1.0       1.00      1.00      1.00      1946

    accuracy                           1.00      2913
   macro avg       1.00      1.00      1.00      2913
weighted avg       1.00      1.00      1.00      2913

model_pressure_O_linearSVC

------------------




Train : 0.9213284132841328
Test : 0.9189838654308273
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.84      0.93      0.88       967
         1.0       0.96      0.91      0.94      1946

    accuracy                           0.92      2913
   macro avg       0.90      0.92      0.91      2913
weighted avg       0.92      0.92      0.92      2913

model_pressure_O_kneighbors

------------------




Train : 0.9533579335793358
Test : 0.9430140748369379
[0. 0. 0. ... 1. 1. 1.]
            

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.9510262405819694
Test : 0.9335949290673106
[0. 0. 0. ... 0. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.91      0.86      0.88       967
         1.0       0.94      0.97      0.95      2346

    accuracy                           0.93      3313
   macro avg       0.93      0.91      0.92      3313
weighted avg       0.93      0.93      0.93      3313

model_magfieldx_X_linearSVC

------------------




Train : 0.8885424785658612
Test : 0.8834892846362813
[0. 0. 0. ... 0. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.78      0.84      0.81       967
         1.0       0.93      0.90      0.92      2346

    accuracy                           0.88      3313
   macro avg       0.86      0.87      0.86      3313
weighted avg       0.89      0.88      0.88      3313

model_magfieldx_X_kneighbors

------------------




Train : 0.9467394128345025
Test : 0.9308783579837006
[0. 0. 0. ... 1. 1. 1.]
          

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.9101107011070111
Test : 0.8853415722622726
[0. 1. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.88      0.76      0.81       967
         1.0       0.89      0.95      0.92      1946

    accuracy                           0.89      2913
   macro avg       0.88      0.85      0.87      2913
weighted avg       0.88      0.89      0.88      2913

model_magfieldx_O_linearSVC

------------------




Train : 0.8559409594095941
Test : 0.8606247854445589
[1. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.72      0.94      0.82       967
         1.0       0.96      0.82      0.89      1946

    accuracy                           0.86      2913
   macro avg       0.84      0.88      0.85      2913
weighted avg       0.88      0.86      0.86      2913

model_magfieldx_O_kneighbors

------------------




Train : 0.957490774907749
Test : 0.9461036731891521
[0. 1. 0. ... 1. 1. 1.]
           

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.9416731618602234
Test : 0.9182010262601872
[0. 0. 1. ... 0. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.88      0.83      0.86       967
         1.0       0.93      0.95      0.94      2346

    accuracy                           0.92      3313
   macro avg       0.91      0.89      0.90      3313
weighted avg       0.92      0.92      0.92      3313

model_magfieldy_X_linearSVC

------------------




Train : 0.9058196934268641
Test : 0.9040144883791126
[0. 1. 0. ... 0. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.90      0.75      0.82       967
         1.0       0.90      0.97      0.93      2346

    accuracy                           0.90      3313
   macro avg       0.90      0.86      0.88      3313
weighted avg       0.90      0.90      0.90      3313

model_magfieldy_X_kneighbors

------------------




Train : 0.9347882566900494
Test : 0.9236341684274072
[0. 1. 1. ... 0. 1. 1.]
          

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.9902583025830258
Test : 0.9818056985925163
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.98      0.96      0.97       967
         1.0       0.98      0.99      0.99      1946

    accuracy                           0.98      2913
   macro avg       0.98      0.98      0.98      2913
weighted avg       0.98      0.98      0.98      2913

model_magfieldy_O_linearSVC

------------------




Train : 0.9291512915129151
Test : 0.924133196017851
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.93      0.83      0.88       967
         1.0       0.92      0.97      0.94      1946

    accuracy                           0.92      2913
   macro avg       0.93      0.90      0.91      2913
weighted avg       0.92      0.92      0.92      2913

model_magfieldy_O_kneighbors

------------------




Train : 0.9560147601476015
Test : 0.9423274974253347
[0. 0. 0. ... 1. 1. 1.]
           

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.8559366069108859
Test : 0.8300633866586176
[1. 1. 1. ... 1. 1. 0.]
              precision    recall  f1-score   support

         0.0       0.74      0.64      0.69       967
         1.0       0.86      0.91      0.88      2346

    accuracy                           0.83      3313
   macro avg       0.80      0.77      0.79      3313
weighted avg       0.83      0.83      0.83      3313

model_velocityx_X_linearSVC

------------------




Train : 0.8063133281371785
Test : 0.7980682161183218
[0. 0. 1. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.62      0.78      0.69       967
         1.0       0.90      0.81      0.85      2346

    accuracy                           0.80      3313
   macro avg       0.76      0.79      0.77      3313
weighted avg       0.82      0.80      0.80      3313

model_velocityx_X_kneighbors

------------------




Train : 0.8564562223954274
Test : 0.8373075762149109
[0. 1. 1. ... 1. 1. 1.]
          

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.8822140221402214
Test : 0.8513559903879162
[0. 0. 1. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.79      0.75      0.77       967
         1.0       0.88      0.90      0.89      1946

    accuracy                           0.85      2913
   macro avg       0.84      0.83      0.83      2913
weighted avg       0.85      0.85      0.85      2913

model_velocityx_O_linearSVC

------------------




Train : 0.8519557195571956
Test : 0.8389975969790594
[1. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.75      0.77      0.76       967
         1.0       0.89      0.87      0.88      1946

    accuracy                           0.84      2913
   macro avg       0.82      0.82      0.82      2913
weighted avg       0.84      0.84      0.84      2913

model_velocityx_O_kneighbors

------------------




Train : 0.8977121771217712
Test : 0.8637143837967731
[1. 1. 1. ... 1. 1. 1.]
          

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.9676539360872954
Test : 0.9468759432538485
[0. 1. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.91      0.91      0.91       967
         1.0       0.96      0.96      0.96      2346

    accuracy                           0.95      3313
   macro avg       0.94      0.94      0.94      3313
weighted avg       0.95      0.95      0.95      3313

model_velocityy_X_linearSVC

------------------




Train : 0.89893478825669
Test : 0.8934500452761848
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.81      0.83      0.82       967
         1.0       0.93      0.92      0.92      2346

    accuracy                           0.89      3313
   macro avg       0.87      0.88      0.87      3313
weighted avg       0.89      0.89      0.89      3313

model_velocityy_X_kneighbors

------------------




Train : 0.9612886464016628
Test : 0.9444612134017507
[0. 0. 0. ... 1. 1. 1.]
            

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.9354981549815499
Test : 0.9224167524888431
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.90      0.86      0.88       967
         1.0       0.93      0.95      0.94      1946

    accuracy                           0.92      2913
   macro avg       0.92      0.91      0.91      2913
weighted avg       0.92      0.92      0.92      2913

model_velocityy_O_linearSVC

------------------




Train : 0.9078966789667897
Test : 0.9069687607277721
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.89      0.83      0.85       967
         1.0       0.92      0.95      0.93      1946

    accuracy                           0.91      2913
   macro avg       0.90      0.89      0.89      2913
weighted avg       0.91      0.91      0.91      2913

model_velocityy_O_kneighbors

------------------




Train : 0.9030258302583026
Test : 0.891520768966701
[0. 1. 0. ... 1. 1. 1.]
           

In [ ]:
def loadmodel(modelsdir, target, tag, methodname):
    path = picout + "model_" + target + "_" + tag + "_" + methodname
    with open(path, 'rb') as f:
        return pickle.load(f)


In [ ]:
modelspath = glob.glob(picout)
    

In [ ]:
import pickle
picout = root_dir + "MLres/"

for target in ["magxy"]:
    for tag, altimages1, labelsources1 in [("X","imgout/0117_1X/","txt/labels1X/"), ("O","imgout/0117_1O/", "txt/labels1O/")]:
        TARGET = target
        #それぞれ1番最後の'/'は忘れずつけること
        ALTIMAGES0 = root_dir + "imgout/0117_not/"#リコネクションなし分割済データフォルダ
        ALTIMAGES1 = root_dir + altimages1#リコネクションあり分割済データフォルダ
        LABEL_SOURCE0 = root_dir + "txt/labels0/"#リコネクションありのラベリングcsvのあるフォルダ
        LABEL_SOURCE1 = root_dir + labelsources1#リコネクションなしのラベリングcsvのあるフォルダ
        IMGSHAPE = (100,10)#出来れば画像サイズはすべて同じで合ってほしい。違うサイズが混じる場合は最も多いサイズを指定すること
        DO_PCA = False #データ圧縮。IMGSHAPEと、データサイズが途方もなく多ければTrueにする。
        randomstate = None #学習時のパラメータ。初期値はNone。結果を固定したければ1とかに設定する。

        ML = MLs.ML(TARGET, ALTIMAGES0, ALTIMAGES1, LABEL_SOURCE0, LABEL_SOURCE1, IMGSHAPE, DO_PCA,randomstate=randomstate)
        def savemodel(model, methodname):
            picout = root_dir + "MLres/"
            path = picout + "model_" + target + "_" + tag + "_" + methodname
            file = open(path, "wb") 
            pickle.dump(model, file)
            file.close()
            print("model_" + target + "_" + tag + "_" + methodname+"\n")
            print("------------------\n\n\n\n")
        model = ML.linearSVC()   
        savemodel(model, "linearSVC")
        model = ML.kneighbors()
        savemodel(model, "kneighbors")
        model = ML.rbfSVC()
        savemodel(model, "rbfSVC")
        model = ML.XGBoost()
        savemodel(model, "XGBoost")

PCA 非実施


c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.9340088334632372
Test : 0.9194083911862361
[1. 0. 1. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.90      0.82      0.86       967
         1.0       0.93      0.96      0.94      2346

    accuracy                           0.92      3313
   macro avg       0.91      0.89      0.90      3313
weighted avg       0.92      0.92      0.92      3313

model_magxy_X_linearSVC

------------------




Train : 0.9172512340867758
Test : 0.9136734077875037
[1. 0. 1. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.98      0.72      0.83       967
         1.0       0.90      0.99      0.94      2346

    accuracy                           0.91      3313
   macro avg       0.94      0.86      0.89      3313
weighted avg       0.92      0.91      0.91      3313

model_magxy_X_kneighbors

------------------




Train : 0.8777604572616264
Test : 0.8744340476909146
[1. 0. 1. ... 1. 1. 1.]
              prec

c:\Users\TsugiKawa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Train : 0.9551291512915129
Test : 0.9364915894267078
[0. 0. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.94      0.87      0.90       967
         1.0       0.94      0.97      0.95      1946

    accuracy                           0.94      2913
   macro avg       0.94      0.92      0.93      2913
weighted avg       0.94      0.94      0.94      2913

model_magxy_O_linearSVC

------------------




Train : 0.8977121771217712
Test : 0.8976999656711294
[0. 1. 0. ... 1. 1. 1.]
              precision    recall  f1-score   support

         0.0       0.99      0.70      0.82       967
         1.0       0.87      1.00      0.93      1946

    accuracy                           0.90      2913
   macro avg       0.93      0.85      0.87      2913
weighted avg       0.91      0.90      0.89      2913

model_magxy_O_kneighbors

------------------




Train : 0.8922509225092251
Test : 0.8870580157912805
[0. 1. 0. ... 1. 1. 1.]
              prec

# npyのパスのdfから画像出力

In [16]:
s = "../imgout/0117_1X/magxy/magxy_77.34.5_37.548.npy"

In [65]:
import re

content = s
content = r"../imgout/0117_1X/magxy/magxy_77.3.1_37.548.npy"
pathPattern = re.compile('_\d+\.\d+\.\d+_')
rangePattern =re.compile('_\d+\.\d+\.npy')
# pattern = '_\d+\.'

pathstr = pathPattern.search(content).group()[1:-1]
rangestr = rangePattern.search(content).group()[1:-4]
print(pathstr, rangestr)
path = pathstr.split(".")
licpath = f"../imgout/ohnolic/snap{path[0]}/lic_snap{path[0]}.{'{0:02d}'.format(int(path[1]))}.{'{0:02d}'.format(int(path[2]))}.bmp"
licpath

imgXlen = 1799
imgYlen = 570
orgx = 257
orgy = 1025
npylocx =123
npylocy = 545
bmplocx = (npylocx*imgXlen/orgx)
bmplocy = (imgYlen-(imgYlen*npylocy/orgy))
# npylocx =  (bmplocx*orgx/imgXlen)
# npylocy =  (orgy-(bmplocy*orgy/imgYlen))

77.3.1 37.548


'./imgout/ohnolic/snap77/lic_snap77.03.01.bmp'

../imgout/0119test/magxy/y0pred1/magxy_77.45.9_39.369.bmp
../imgout/ohnolic/snap77/lic_snap77.45.09.bmp
[[ 0 59 61 ... 65 63  0]
 [ 1 62 62 ... 71 69  3]
 [ 3 66 68 ... 64 63  2]
 ...
 [ 1 61 62 ... 62 62  0]
 [ 2 68 68 ... 66 65  3]
 [ 3  2  0 ...  1  1  2]]
308 238 336 392
[[123 127 124 ... 129 131 127]
 [126 129 128 ... 137 139 142]
 [127 126 128 ... 131 132 129]
 ...
 [133 132 131 ... 126 134 128]
 [119 121 128 ... 119 117 128]
 [127 126 122 ... 139 130 126]]
../imgout/0119test/magxy/y0pred1/magxy_77.45.9_39.369.bmp
../imgout/0119test/magxy/y0pred1/magxy_77.47.9_39.369.bmp
../imgout/ohnolic/snap77/lic_snap77.47.09.bmp
[[ 2 66 65 ... 63 61  1]
 [ 0 70 72 ... 62 60  2]
 [ 3 66 66 ... 66 64  0]
 ...
 [ 2 69 71 ... 67 66  0]
 [ 2 63 63 ... 59 58  3]
 [ 2  2  1 ...  0  2  1]]
308 238 336 392
[[124 122 122 ... 127 123 121]
 [136 139 139 ... 118 121 123]
 [130 133 133 ... 129 128 128]
 ...
 [128 126 129 ... 139 134 132]
 [129 129 129 ... 134 136 135]
 [123 120 122 ... 129 129 129]]
../img

In [73]:
df1

path    y predict
48    ../imgout/0117_not/magxy/magxy_77.45.9_39.369.npy  0.0     1.0
70    ../imgout/0117_not/magxy/magxy_77.47.9_39.369.npy  0.0     1.0
107   ../imgout/0117_not/magxy/magxy_77.24.5_158.554...  0.0     1.0
125   ../imgout/0117_not/magxy/magxy_77.23.9_115.498...  0.0     1.0
166   ../imgout/0117_not/magxy/magxy_49.19.10_65.546...  0.0     1.0
...                                                 ...  ...     ...
2577   ../imgout/0117_1X/magxy/magxy_77.34.5_37.548.npy  1.0     0.0
2909  ../imgout/0117_1X/magxy/magxy_77.6.11_213.559.npy  1.0     0.0
2916  ../imgout/0117_1X/magxy/magxy_77.48.10_241.570...  1.0     0.0
3140  ../imgout/0117_1X/magxy/magxy_49.58.13_134.505...  1.0     0.0
3231   ../imgout/0117_1X/magxy/magxy_49.24.9_25.480.npy  1.0     0.0

[72 rows x 3 columns]

In [95]:
for i, j in zip(df1["path"], df1["y"]):
    print(j)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
